import {expect, test} from "vitest";
import {ArmletAssemblyParser} from "@/architectures/armlet/parser.js";
import {
    AddImmediateInstruction,
    AndImmediateInstruction,
    ArmletInstructionFactory,
    AsrImmediateInstruction,
    AsrInstruction,
    BabImmediateInstruction,
    BabInstruction,
    BaeImmediateInstruction,
    BaeInstruction,
    BbeImmediateInstruction,
    BbeInstruction,
    BbwImmediateInstruction,
    BbwInstruction,
    BeqImmediateInstruction,
    BeqInstruction,
    BgeImmediateInstruction,
    BgeInstruction,
    BgtImmediateInstruction,
    BgtInstruction,
    BleImmediateInstruction,
    BleInstruction,
    BltImmediateInstruction,
    BltInstruction,
    BneImmediateInstruction,
    BneInstruction,
    CmpImmediateInstruction,
    CmpInstruction,
    EorImmediateInstruction,
    EorInstruction,
    IorImmediateInstruction,
    IorInstruction,
    JmpImmediateInstruction,
    JmpInstruction,
    LoaInstruction,
    LslImmediateInstruction,
    LslInstruction,
    LsrImmediateInstruction,
    LsrInstruction,
    MovImmediateInstruction,
    MovInstruction,
    NegInstruction,
    NopInstruction,
    StoInstruction,
    SubImmediateInstruction,
    SubInstruction
} from "@/architectures/armlet/instructions.js";
import {AddInstruction, AndInstruction, NotInstruction} from "@/architectures/anna/instructions.js";

test('test parsing programm with all instructions', () => {
    let program = [
        "nop",
        "mov $0, $1",
        "mov $0, 123",
        "and $0, $1, $2",
        "and $0, $1, 123",
        "ior $0, $1, $2",
        "ior $0, $1, 123",
        "eor $0, $1, $2",
        "eor $0, $1, 123",
        "not $0, $1",
        "add $0, $1, $2",
        "add $0, $1, 123",
        "sub $0, $1, $2",
        "sub $0, $1, 123",
        "neg $0, $1",
        "lsl $0, $1, $2",
        "lsl $0, $1, 1",
        "lsr $0, $1, $2",
        "lsr $0, $1, 1",
        "asr $0, $1, $2",
        "asr $0, $1, 1",
        "loa $0, $1",
        "sto $0, $1",
        "cmp $0, $1",
        "cmp $0, 1",
        "jmp $1",
        "beq $1",
        "bne $1",
        "bgt $1",
        "blt $1",
        "bge $1",
        "ble $1",
        "bab $1",
        "bbw $1",
        "bae $1",
        "bbe $1",
        "jmp 1",
        "beq 1",
        "bne 1",
        "bgt 1",
        "blt 1",
        "bge 1",
        "ble 1",
        "bab 1",
        "bbw 1",
        "bae 1",
        "bbe 1",
    ]

    let expectedProgram = [
        new NopInstruction(),
        new MovInstruction(['$0', '$1']),
        new MovImmediateInstruction(['$0', '123']),
        new AndInstruction(['$0', '$1', '$2']),
        new AndImmediateInstruction(['$0', '$1', '123']),
        new IorInstruction(['$0', '$1', '$2']),
        new IorImmediateInstruction(['$0', '$1', '123']),
        new EorInstruction(['$0', '$1', '$2']),
        new EorImmediateInstruction(['$0', '$1', '123']),
        new NotInstruction(['$0', '$1']),
        new AddInstruction(['$0', '$1', '$2']),
        new AddImmediateInstruction(['$0', '$1', '123']),
        new SubInstruction(['$0', '$1', '$2']),
        new SubImmediateInstruction(['$0', '$1', '123']),
        new NegInstruction(['$0', '$1']),
        new LslInstruction(['$0', '$1', '$2']),
        new LslImmediateInstruction(['$0', '$1', '1']),
        new LsrInstruction(['$0', '$1', '$2']),
        new LsrImmediateInstruction(['$0', '$1', '1']),
        new AsrInstruction(['$0', '$1', '$2']),
        new AsrImmediateInstruction(['$0', '$1', '1']),
        new LoaInstruction(['$0', '$1']),
        new StoInstruction(['$0', '$1']),
        new CmpInstruction(['$0', '$1']),
        new CmpImmediateInstruction(['$0', "1"]),
        new JmpInstruction(['$1']),
        new BeqInstruction(['$1']),
        new BneInstruction(['$1']),
        new BgtInstruction(['$1']),
        new BltInstruction(['$1']),
        new BgeInstruction(['$1']),
        new BleInstruction(['$1']),
        new BabInstruction(['$1']),
        new BbwInstruction(['$1']),
        new BaeInstruction(['$1']),
        new BbeInstruction(['$1']),
        new JmpImmediateInstruction(['1']),
        new BeqImmediateInstruction(['1']),
        new BneImmediateInstruction(['1']),
        new BgtImmediateInstruction(['1']),
        new BltImmediateInstruction(['1']),
        new BgeImmediateInstruction(['1']),
        new BleImmediateInstruction(['1']),
        new BabImmediateInstruction(['1']),
        new BbwImmediateInstruction(['1']),
        new BaeImmediateInstruction(['1']),
        new BbeImmediateInstruction(['1']),
    ]

    let parser = new ArmletAssemblyParser(new ArmletInstructionFactory());
    let parsedProgram = parser.parseCode(program.join('\n'))

    expect(parsedProgram).toEqual(expectedProgram);
});